<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_penyakit extends CI_Model
{

    public $table = 'penyakit';
    public $id = 'id_penyakit';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_penyakit', $q);
	$this->db->or_like('kd_penyakit', $q);
	$this->db->or_like('penyakit', $q);
	$this->db->or_like('g1', $q);
	$this->db->or_like('g2', $q);
	$this->db->or_like('g3', $q);
	$this->db->or_like('g4', $q);
	$this->db->or_like('g5', $q);
	$this->db->or_like('c1', $q);
	$this->db->or_like('c2', $q);
	$this->db->or_like('c3', $q);
	$this->db->or_like('c4', $q);
	$this->db->or_like('c5', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_penyakit', $q);
	$this->db->or_like('kd_penyakit', $q);
	$this->db->or_like('penyakit', $q);
	$this->db->or_like('g1', $q);
	$this->db->or_like('g2', $q);
	$this->db->or_like('g3', $q);
	$this->db->or_like('g4', $q);
	$this->db->or_like('g5', $q);
	$this->db->or_like('c1', $q);
	$this->db->or_like('c2', $q);
	$this->db->or_like('c3', $q);
	$this->db->or_like('c4', $q);
	$this->db->or_like('c5', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file M_penyakit.php */
/* Location: ./application/models/M_penyakit.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-28 10:22:06 */
/* http://harviacode.com */